### ISSUE TITLE
AWS ECR domain issue

### ISSUE THREAD

**Issue by bwang221** [whereisaaron/kubernetes-aws-scripts#1]
I am not sure how this worked for you, i assume that ${ACCOUNT} is a number on AWS
this command will throw an error like this:

The Secret "XXXXX" is invalid: metadata.name: Invalid value: "XXXXX": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

kubectl create secret docker-registry $SECRET_NAME \
 --docker-server=https://${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com \
 --docker-username=AWS \
 --docker-password="${TOKEN}" \
 --docker-email="${EMAIL}"

**Comment by whereisaaron** [comment]
Hi @bwang221 it is the $SECRET_NAME it is objecting to. There were some versions of `kubectl` and one version of k8s 1.8.x that had incorrect validation of names. So I would suggest you try a bit newer version of `kubectl`. Alternatively you can check or change the secret name to keep the validation happy.

**Comment by brianwang-wk** [comment]
Thanks! you are right, it is the name that caused the problem, but the error message is so misleading.

**Comment by whereisaaron** [comment]
Hi @bwang221 I haven't heard back for a while so I'll close this. But if you have the problem with the current `kubectl` you can reopen.
